services:
  - type: web
    name: springboot-01
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/SpringBoot_01-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.jdk
